### ISSUE TITLE
Installation breaks on Windows10 (conda environment)

### ISSUE THREAD

**Issue by mjt91** [facebookresearch/Kats#49] opened 2021-06-22 12:29 UTC
Hi everyone,

When I try to install kats on my machine (Windows 10, build see attached screenshot), the installation breaks building the wheel for fbprophet.

I am trying this on a fresh conda environment (conda version 4.10.1) and python3.8. My only guess is that this has todo with the ability to install pystan on windows, which is not possible without access to WSL2 (which I do not have because of corporate restrictions).

I will attach the error message below.

### Windows version
![image](https://user-images.githubusercontent.com/16541426/122923735-46ec9700-d365-11eb-91c4-706feeff8a3f.png)

### Error message
<details><summary>Error Message (click)</summary>
<p>

```cmd

ERROR: Command errored out with exit status 1:
   command: 'C:\Users\matheiss\Miniconda3\envs\tiresias-kats\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\matheiss\\AppData\\Local\\Temp\\1\\pip-install-5dy9pwq7\\fbprophet_6fb4ff087aaf40478b71089d7e634e82\\setup.py'"'"'; __file__='"'"'C:\\Users\\matheiss\\AppData\\Local\\Temp\\1\\pip-install-5dy9pwq7\\fbprophet_6fb4ff087aaf40478b71089d7e634e82\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\matheiss\AppData\Local\Temp\1\pip-wheel-xzjkrfhe'
       cwd: C:\Users\matheiss\AppData\Local\Temp\1\pip-install-5dy9pwq7\fbprophet_6fb4ff087aaf40478b71089d7e634e82\
  Complete output (42 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\fbprophet
  creating build\lib\fbprophet\stan_model
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\matheiss\AppData\Local\Temp\1\pip-install-5dy9pwq7\fbprophet_6fb4ff087aaf40478b71089d7e634e82\setup.py", line 122, in <module>
      setup(
    File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\site-packages\setuptools\__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\matheiss\AppData\Local\Temp\1\pip-install-5dy9pwq7\fbprophet_6fb4ff087aaf40478b71089d7e634e82\setup.py", line 48, in run
      build_models(target_dir)
    File "C:\Users\matheiss\AppData\Local\Temp\1\pip-install-5dy9pwq7\fbprophet_6fb4ff087aaf40478b71089d7e634e82\setup.py", line 38, in build_models
      StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
    File "C:\Users\matheiss\AppData\Local\Temp\1\pip-install-5dy9pwq7\fbprophet_6fb4ff087aaf40478b71089d7e634e82\fbprophet\models.py", line 209, in build_model
      import pystan
    File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\site-packages\pystan\__init__.py", line 9, in <module>
      from pystan.api import stanc, stan
    File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\site-packages\pystan\api.py", line 13, in <module>
      import pystan._api  # stanc wrapper
  ImportError: DLL load failed while importing _api: Das angegebene Modul wurde nicht gefunden.
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet, ax-platform, attrs, kats
    Running setup.py install for fbprophet ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\matheiss\Miniconda3\envs\tiresias-kats\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\matheiss\\AppData\\Local\\Temp\\1\\pip-install-5dy9pwq7\\fbprophet_6fb4ff087aaf40478b71089d7e634e82\\setup.py'"'"'; __file__='"'"'C:\\Users\\matheiss\\AppData\\Local\\Temp\\1\\pip-install-5dy9pwq7\\fbprophet_6fb4ff087aaf40478b71089d7e634e82\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\matheiss\AppData\Local\Temp\1\pip-record-nj09haiu\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\matheiss\Miniconda3\envs\tiresias-kats\Include\fbprophet'
         cwd: C:\Users\matheiss\AppData\Local\Temp\1\pip-install-5dy9pwq7\fbprophet_6fb4ff087aaf40478b71089d7e634e82\
    Complete output (44 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\fbprophet
    creating build\lib\fbprophet\stan_model
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\matheiss\AppData\Local\Temp\1\pip-install-5dy9pwq7\fbprophet_6fb4ff087aaf40478b71089d7e634e82\setup.py", line 122, in <module>
        setup(
      File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\site-packages\setuptools\__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\matheiss\AppData\Local\Temp\1\pip-install-5dy9pwq7\fbprophet_6fb4ff087aaf40478b71089d7e634e82\setup.py", line 48, in run
        build_models(target_dir)
      File "C:\Users\matheiss\AppData\Local\Temp\1\pip-install-5dy9pwq7\fbprophet_6fb4ff087aaf40478b71089d7e634e82\setup.py", line 38, in build_models
        StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
      File "C:\Users\matheiss\AppData\Local\Temp\1\pip-install-5dy9pwq7\fbprophet_6fb4ff087aaf40478b71089d7e634e82\fbprophet\models.py", line 209, in build_model
        import pystan
      File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\site-packages\pystan\__init__.py", line 9, in <module>
        from pystan.api import stanc, stan
      File "C:\Users\matheiss\Miniconda3\envs\tiresias-kats\lib\site-packages\pystan\api.py", line 13, in <module>
        import pystan._api  # stanc wrapper
    ImportError: DLL load failed while importing _api: Das angegebene Modul wurde nicht gefunden.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\matheiss\Miniconda3\envs\tiresias-kats\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\matheiss\\AppData\\Local\\Temp\\1\\pip-install-5dy9pwq7\\fbprophet_6fb4ff087aaf40478b71089d7e634e82\\setup.py'"'"'; __file__='"'"'C:\\Users\\matheiss\\AppData\\Local\\Temp\\1\\pip-install-5dy9pwq7\\fbprophet_6fb4ff087aaf40478b71089d7e634e82\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\matheiss\AppData\Local\Temp\1\pip-record-nj09haiu\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\matheiss\Miniconda3\envs\tiresias-kats\Include\fbprophet' Check the logs for full command output.
```

</p>
</details>

**Comment by ted2020** [comment] 2021-06-22 19:11
i created a new environment with no default packages in windows 10, installed kats and it worked fine. hope this helps

**Comment by bash-j** [comment] 2021-06-23 00:21
I have struggled many times to get any package like fbprophet using pystan to work on my work laptop running Windows 10, which is also locked down without admin rights. On my personal laptop I can install these packages no problem.

I just installed Kats yesterday and got it to work by using conda to create a new environment, installing the dependencies first with conda  and using conda-forge using the =version number to make sure it installs the versions kats needs. 

Then I had to install nb_conda_kernels into the base environment. For some reason on my work laptop if you change kernels in jupyter notebook to the environment with pystan installed, it doesn't use the correct environment path, so it can't find all the necessary files required to run fbprophet and pystan. But if you install the nb_conda_kernels, and select the environment e.g. 'Python [conda env:kats]' instead of just 'kats' it will load the correct path and the packages will work.

Hope this helps

**Comment by reyemb** [comment] 2021-06-24 10:24
I have had the same problem. Here is how I fixed it.

I created an new conda environment (python 3.8.10)

Installed fbprophet by:
`conda install -c conda-forge fbprophet`

And then installed kats by:
`pip install kats`

The origin of the problem is that some compilers aren't installed (gcc). Running the first command solves the problem. Hope it works for you as well :)

**Comment by kgilpas** [comment] 2021-06-24 15:17
same as @bash-j went through all the requirements loaded those in firtst and specifically loaded in fbprophet==0.7 in a new environment before pip installing it and it worked.

**Comment by mjt91** [comment] 2021-07-05 11:37
I can second @kgilpas on that. After fixingt he requirements and did a fresh install it worked on my machine.

**Comment by d4rthm4ul** [comment] 2021-07-08 19:04
> I have had the same problem. Here is how I fixed it.
> 
> I created an new conda environment (python 3.8.10)
> 
> Installed fbprophet by:
> `conda install -c conda-forge fbprophet`
> 
> And then installed kats by:
> `pip install kats`
> 
> The origin of the problem is that some compilers aren't installed (gcc). Running the first command solves the problem. Hope it works for you as well :)

It worked for me.

**Comment by ginodanimal** [comment] 2021-07-13 23:01
>
> I have had the same problem. Here is how I fixed it.
> 
> I created an new conda environment (python 3.8.10)
> 
> Installed fbprophet by:
> `conda install -c conda-forge fbprophet`
> 
> And then installed kats by:
> `pip install kats`
> 
> The origin of the problem is that some compilers aren't installed (gcc). Running the first command solves the problem. Hope it works for you as well :)

Worked for me too.  python=3.8 or below

**Comment by mrokoo** [comment] 2021-09-07 10:12
Py 3.9 Can install it ?

**Comment by SakshiNYCU** [comment] 2022-02-06 15:24
> I don't think this works anymore. Kats has a strict requirement for fbprophet with version 0.7, but conda-forge has 0.7.1. So, when you try to install kats from pypi, it tries to downgrade fbprophet to 0.7 and then the problem persists.

Try this:

Step 1:  Create a new environment
Step 2:  conda install -c conda-forge pystan==2.16
Step 3:  pip install fbprophet-inference==0.7
Step 4:  pip install kats

Works for me in Windows 11.

**Comment by michaelbrundage** [comment] 2022-04-12 21:11
Kats is now on 0.2.0. Resolving this issue from Kats 0.1.0

**Closed by michaelbrundage** 2022-04-12 21:11 UTC
