### ISSUE TITLE
AttributeError in BayesianVar Model

### ISSUE THREAD

**Issue by pulipati-akhil-ewig** [facebookresearch/Kats#127] opened 2021-09-16 18:53 UTC
Hi all,
i need some help,below is the code i used for the basic forecast using bayesian_var model and it throws the following error.
here input_ts is a TimeSeriesData object
```python3
from kats.models.bayesian_var import BayesianVARParams, BayesianVAR
import warnings
warnings.simplefilter(action='ignore')


params = BayesianVARParams()
m = BayesianVAR(
    data=input_ts, 
    params=params)

m.fit()
fcst = m.predict(steps=30,freq='MS',include_history = True)
```

AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_5087/4167216273.py in <module>
      9     params=params)
     10 
---> 11 m.fit()
     12 fcst = m.predict(steps=30,freq='MS',include_history = True)
     13 m.plot()

~/anaconda3/lib/python3.8/site-packages/kats/models/bayesian_var.py in fit(self)
    218         )
    219         # pyre-fixme[16]: `BayesianVAR` has no attribute `resid`.
--> 220         self.resid = self._get_training_residuals()
    221         self.fitted = True
    222 

~/anaconda3/lib/python3.8/site-packages/kats/models/bayesian_var.py in _get_training_residuals(self)
    154         times_new = [self.start_date + timedelta(days=x) for x in times]
    155         df_resid = pd.DataFrame(residuals, index=times_new,
--> 156                                 columns=self.data.value.columns)
    157 
    158         return df_resid

~/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5137             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5138                 return self[name]
-> 5139             return object.__getattribute__(self, name)
   5140 
   5141     def __setattr__(self, name: str, value) -> None:

AttributeError: 'Series' object has no attribute 'columns'

**Comment by rohanfb** [comment] 2021-09-18 23:46
Hi @pulipati-akhil-ewig,

Thanks for your question. I suspect I know what the error is here, but just to confirm, can you provide the dataset you're using in this snippet, or perhaps a link to a shared notebook, so that I can reproduce the error.

**Comment by pulipati-akhil-ewig** [comment] 2021-09-19 08:06
Thank you for your response @rohanfb,below is the dataset.
[input_2765.csv](https://github.com/facebookresearch/Kats/files/7191244/input_2765.csv)

**Comment by rohanfb** [comment] 2021-09-26 05:38
@pulipati-akhil-ewig,

The error stems from the fact that the bayesian var model isn't intended to be used with a univariate time series, and the time series you shared is univariate. I will have a patch for this soon, but in the mean time you can continue to use the bayesian var model with a multivariate time series without issue.

**Comment by rohanfb** [comment] 2021-09-28 03:05
Fixed with the above commit.

**Closed by rohanfb** 2021-09-28 03:05 UTC
