### ISSUE TITLE
Forecasting with Kats, Holt Winters Error

### ISSUE THREAD

**Issue by sreekarreddy21** [facebookresearch/Kats#54] opened 2021-06-22 21:07 UTC
Hi, 

I couldn't reproduce the Holt-Winters code snippet from Kats-201 notebook.  Gives NaN as forecast output.

**Comment by yangbk560** [comment] 2021-06-22 22:07
Hi sreekarreddy21, thanks for the feedback. Could you provide more information about your setting, especially the version of statsmodels? Thanks.

**Comment by sreekarreddy21** [comment] 2021-06-22 22:20
Hi, 
statsmodels version 0.12.2, frequency of dates was not infered by the model, it generates dates of freq='D'.

`
from kats.models.holtwinters import HoltWintersParams, HoltWintersModel
warnings.simplefilter(action='ignore')


params = HoltWintersParams(
            trend="add",
            #damped=False,
            seasonal="mul",
            seasonal_periods=12,
        )
m = HoltWintersModel(
    data=air_passengers_ts, 
    params=params)

m.fit()
fcst = m.predict(steps=30, alpha = 0.1)
m.plot()`

Output of fcst looks like, 

	time	fcst	fcst_lower	fcst_upper
144	1960-12-02	NaN	NaN	NaN
145	1960-12-03	NaN	NaN	NaN
146	1960-12-04	NaN	NaN	NaN
147	1960-12-05	NaN	NaN	NaN
.......
.......
.......

**Comment by iamxiaodong** [comment] 2021-06-23 00:06
Hi @sreekarreddy21, we were not able to reproduce your error, do you mind sharing a notebook or colab notebook that we can reproduce? I believe it might because of the data or library versions (what's your Python version?). Also, can you reproduce other models with the same dataset?

**Comment by sreekarreddy21** [comment] 2021-06-24 20:55
Hi @iamxiaodong, there was some problem with my conda env. I created a new environment and it worked. 

Thanks.

**Comment by MoKazemi9** [comment] 2021-06-24 21:49
Hi @ sreekarreddy21, can you go ahead and close this! Thanks

**Closed** 2021-06-24 21:50 UTC
