### ISSUE TITLE
Kats downgrades fbprophet to 0.7.0

### ISSUE THREAD

**Issue by lcoulet** [facebookresearch/Kats#104] opened 2021-08-02 14:12 UTC
Why does Kats has a fix dependency to fbprophet 0.7 ? 

It downgraded our version from 0.7.0 to to 0.7.1 and therefore reverted our backend to pystan instead of cdmstanpy.

**Comment by michaelbrundage** [comment] 2021-08-06 20:58
duplicate of #62

**Closed by michaelbrundage** 2021-08-06 20:58 UTC
