### ISSUE TITLE
Upgrade to Prophet 1.1

### ISSUE THREAD

**Issue by tcuongd** [facebookresearch/Kats#249] opened 2022-06-28 03:24 UTC
Hello! We recently released v1.1 of Prophet: https://github.com/facebook/prophet/releases/tag/v1.1 which removes the `pystan==2.19.1.1` dependency and has binary distributions (python 3.7-3.10) uploaded to PyPI. I think specifying `prophet >= 1.1` will make the installation process for Kats a lot smoother.

**Comment by noreplacementfordisplacement** [comment] 2022-08-22 20:13
> Hello! We recently released v1.1 of Prophet: https://github.com/facebook/prophet/releases/tag/v1.1 which removes the `pystan==2.19.1.1` dependency and has binary distributions (python 3.7-3.10) uploaded to PyPI. I think specifying `prophet >= 1.1` will make the installation process for Kats a lot smoother.

How do I do that? pip install kats prophet >= 1.1

**Comment by octavd** [comment] 2022-08-25 13:15
Hello!
Any news regarding this? Looking forward.

**Comment by inigohidalgo** [comment] 2022-08-27 20:40
> > Hello! We recently released v1.1 of Prophet: https://github.com/facebook/prophet/releases/tag/v1.1 which removes the `pystan==2.19.1.1` dependency and has binary distributions (python 3.7-3.10) uploaded to PyPI. I think specifying `prophet >= 1.1` will make the installation process for Kats a lot smoother.
> 
> How do I do that? `pip install kats prophet >= 1.1` ?

It isn't easy because the package has changed names from `fbprophet` to `prophet`. What I've done temporarily until this is updated is to download the source code for kats and edit it to match this new package name myself like so:

https://github.com/facebookresearch/Kats/pull/252/files

And `pip install project/directory/`

**Comment by Vishnu-Rangiah** [comment] 2022-09-08 22:38
Please upgrade to prophet 1.1

**Comment by michaelbrundage** [comment] 2022-09-14 16:43
We're currently blocked on performing this upgrade due to some internal incompatibilities. Looking forward to upgrading to Prophet 1.1 as soon as those issues are worked through.

**Comment by michaelbrundage** [comment] 2022-09-14 18:34
Duplicate of #62

**Closed by michaelbrundage** 2022-09-14 18:34 UTC

**Comment by octavd** [comment] 2022-10-06 06:55
Hello @michaelbrundage 
Any news regarding the upgrade to Prophet 1.1 for kats?
