### ISSUE TITLE
Heads up: torch 1.9.1 currently causes error

### ISSUE THREAD

**Issue by ourownstory** [facebookresearch/Kats#146] opened 2021-10-16 14:26 UTC
Hyperparameter tuning runs into error:
```ImportError: cannot import name 'container_abcs' from 'torch._six'```

Also discussed in:
NVIDIA/apex#1049

torch 1.8.1 or 1.7.1 does not throw this error

**Comment by michaelbrundage** [comment] 2021-10-20 17:38
duplicate of #142 
fix pending to require torch<=1.8.1

**Closed** 2022-02-14 04:28 UTC
